server:
  port: 6325

spring:
  elasticsearch:
    jest:
      uris:
        - http://jd-search-elk:9200
      read-timeout: 5000
  datasource:
    url: jdbc:mysql://jd-search-mysql:3306/crawler_data?autoReconnect=true&useSSL=false
    username: docker
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
    type-aliases-package: com.quick.es.entity
    mapper-locations: classpath*:/mapper/*Mapper.xml
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
