version: '2'

services:
    mysql:
        build: .
        ports:
            - "3306:3306"

    elk:
        image: sebp/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
            - "5045:5045"
            - "5046:5046"
